version: '3.1'

services:
  postgres:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
  hhn-helpdesk-backend:
    build:
      context: ./hhn-helpdesk-backend
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=foo=bar
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    links:
      - postgres
    depends_on:
      - postgres
    restart: always
  hhn-helpdesk-frontend:
    build:
      context: ./hhn-helpdesk-frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    links:
      - postgres
      - hhn-helpdesk-backend
    depends_on:
      - postgres
      - hhn-helpdesk-backend
    restart: always
volumes:
  pg-data: